name: testing
on:
    push:
        branches:
            - main

jobs:
  reward:
    runs-on : ubuntu-latest
    name :  Add points
    steps:
      - name: Leaderboard Points
        uses: saitejach127/osf-testing@v1.1

