name: Labeling issue 
on:
  issues:
    types: ['opened', 'edited']
  pull_request:
    types: ['opened', 'edited']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: tjgurwara99/label-maker@v0.1.2
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
